module.exports={
    entry:{
        main:"./src/main.js"
    },
    module:{
        rules:[
            {
                test:/\.js$/,
                loader:'babel-loader',
                options:{
                    presets:['@babel/preset-env'],
                    plugins:[['@babel/plugin-transform-react-jsx',{pragma:"zK_creatElement"}]]
                }
            }
        ]
    },
    mode:"development",
    optimization:{
        minimize:false,
    }
}